// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYy_rqZMZQ_aGcUPP2exKRwWB8m3FHj58',
    appId: '1:1056160130840:web:d977b411f03d870199a06d',
    messagingSenderId: '1056160130840',
    projectId: 'smsakimat',
    authDomain: 'smsakimat.firebaseapp.com',
    storageBucket: 'smsakimat.firebasestorage.app',
    measurementId: 'G-DVYV2E6NH0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoNB1hqD7c-4dsFgrCP-SoHgxggXTq4eE',
    appId: '1:1056160130840:android:eb7fd03e606f7fef99a06d',
    messagingSenderId: '1056160130840',
    projectId: 'smsakimat',
    storageBucket: 'smsakimat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8rTWmDNikVIatlDN4ED1XfSFfYKry3Fc',
    appId: '1:1056160130840:ios:5aab93a1634f1acd99a06d',
    messagingSenderId: '1056160130840',
    projectId: 'smsakimat',
    storageBucket: 'smsakimat.firebasestorage.app',
    iosBundleId: 'com.example.akimatProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYy_rqZMZQ_aGcUPP2exKRwWB8m3FHj58',
    appId: '1:1056160130840:web:2dfd89cff9d8a56799a06d',
    messagingSenderId: '1056160130840',
    projectId: 'smsakimat',
    authDomain: 'smsakimat.firebaseapp.com',
    storageBucket: 'smsakimat.firebasestorage.app',
    measurementId: 'G-9Q7T068LE7',
  );
}
